# Dockerfile
FROM node:22

RUN mkdir -p /app/node_modules
RUN chown -R node:node /app

WORKDIR /app

COPY . .

RUN rm -rf packages/frontend-desktop
RUN rm -rf packages/frontend-web

RUN npm install

EXPOSE 3000
